### ISSUE TITLE
How to increase precision of decimal fields?

### ISSUE THREAD

**Issue by thbar** [dinedal/textql#40]
If I have this file as input:

```csv
amount
10.01
20
```

then doing a sum gives a low-precision output:

```shell
$ textql -header=true -sql="select sum(amount) from tbl" < input.csv
30.009999999999998
```

Is there a way to increase the precision, in order to get 30.01 here? (like with say `BigDecimal` in Ruby)?

**Comment by dinedal** [comment]
`textql -header=true -sql="select round(sum(amount),2) from tbl" < input.csv` will get you the answer you want. Ref: https://www.sqlite.org/lang_corefunc.html

Something to keep in mind is that the data types you have access to in textql are the same as SQLite. Ref: https://www.sqlite.org/datatype3.html 

The data itself starts out as TEXT but when you apply `sum` it becomes the `NUMERIC` affinity type, which in this case would become the REAL type since one of the rows can not become a INTEGER type without a lossy conversion.

**Comment by thbar** [comment]
Thanks for the clarification! I have a better understanding now. I was already using the `round/printf` trick (like [here](http://stackoverflow.com/a/31149946/20302) where I mention TextQL to compute aggregates) but wondered if there was a better way or not.

Should I close this issue, or do you prefer to keep it opened in order to add a FAQ later maybe (assuming this question may come again)?

**Comment by dinedal** [comment]
I'm going to close it because v2.0 will have a type inference system that will change how this works for the better in most cases, and this answer may no longer apply, or may be different.

A FAQ is a good idea though, thank you!
